kind: pipeline
name: default

trigger:
  branch:
    - main

steps: 
  - name: build
    image: docker:latest
    depends_on: [ clone ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t mesg:1.0.0.$$DRONE_BUILD_NUMBER -f "build/Mesg.Dockerfile" .

  - name: test
    image: docker:dind
    depends_on: [ build ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock    
    commands:
      - docker stop mesg-testing || true
      - docker rm mesg-testing || true
      - docker run -d -p 172.17.0.1:37000:35000 --name mesg-testing mesg:1.0.0.$$DRONE_BUILD_NUMBER
      - docker build -t mesg-testing:1.0.0.$$DRONE_BUILD_NUMBER --name mesg-testing -f "build/Mesg.Testing.Dockerfile" .
      - docker stop mesg-testing || true
      - docker rm mesg-testing || true
    environment:
      MESG_URL: http://172.17.0.1:37000

  - name: clear
    image: docker:dind
    depends_on: [ test ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop mesg || true
      - docker rm mesg || true

  - name: deploy
    image: docker:dind
    depends_on: [ clear ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker run -d -p 172.17.0.1:35000:35000 -p 172.17.0.1:35001:35001 --restart always --name mesg mesg:1.0.0.$$DRONE_BUILD_NUMBER

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock