[package]
name = "mesg"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
hyper = { version = "0.14.15", features = ["full"] }
toml = "0.5.8"
lz4 = "1.23.2"
serde = "1.0.130"
tonic = "0.6.1"
prost = "0.9.0"
timer = "0.2.0"
chrono = "0.4.19"
log = { version = "0.4.14", features = ["release_max_level_error"] }
env_logger = "0.9.0"
clap = "2.33.3"
bytes = "1.1.0"
oneshot = "0.1.2"
chashmap = "2.2.2"
futures = "0.3.17"
async-trait = "0.1.51"
color-eyre = "0.5.11"
thiserror = "1.0.30"
anyhow = "1.0.45"

[build-dependencies]
tonic-build = "0.6.0"
