[package]
name = "mesg"
version = "0.3.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.20.1", features = ["full"] }
hyper = { version = "0.14.20", features = ["full"] }
toml = "0.5.9"
lz4 = "1.24.0"
serde = "1.0.144"
tonic = "0.8.0"
prost = "0.11.0"
timer = "0.2.0"
chrono = "0.4.22"
log = { version = "0.4.17", features = ["release_max_level_info"] }
env_logger = "0.9.0"
bytes = "1.2.1"
oneshot = "0.1.4"
chashmap = "2.2.2"
futures = "0.3.24"
async-trait = "0.1.57"
color-eyre = "0.6.2"
thiserror = "1.0.33"
anyhow = "1.0.63"
structopt = "0.3.26"
lazy_static = "1.4.0"
sled = "0.34.7"
thread-id = "4.0.0"
rand = "0.8.5"
dashmap = "5.4.0"

[build-dependencies]
tonic-build = "0.8.0"
prost-build = "0.11.1"
