[package]
name = "mesg"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"


[dependencies]
tokio = { version = "1.9.0", features = ["full"] }
toml = "0.5.8"
lz4 = "1.23.2"
serde = "1.0.126"
tonic = "0.5.0"
prost = "0.8.0"
timer = "0.2.0"
chrono = "0.4.19"
log = { version = "0.4.14", features = ["release_max_level_info"] }
env_logger = "0.9.0"
clap = "2.33.3"
bytes = "1.0.1"
oneshot = "0.1.2"
parking_lot = "0.11.1"

[build-dependencies]
tonic-build = "0.5.1"
