[package]
name = "mesg"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"


[dependencies]
tokio = { version = "0.2.23", features = ["full"] }
toml = "0.5.7"
lz4 = "1.23.2"
serde = "1.0.117"
tonic = "0.3.1"
prost = "0.6.1"
timer = "0.2.0"
chrono = "0.4.19"
crossbeam-channel = "0.5.0"
dashmap = "3.11.10"
log = { version = "0.4.11", features = ["release_max_level_info"] }
env_logger = "0.8.1"
clap = "2.33.3"
bytes = "0.6.0"
oneshot = "0.1.2"

[build-dependencies]
tonic-build = "0.3.1"
