[package]
name = "mesg"
version = "0.3.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.24.1", features = ["full"] }
hyper = { version = "0.14.23", features = ["full"] }
toml = "0.5.10"
lz4 = "1.24.0"
serde = "1.0.152"
tonic = "0.8.3"
prost = "0.11.6"
timer = "0.2.0"
chrono = "0.4.23"
log = { version = "0.4.17", features = ["release_max_level_info"] }
env_logger = "0.10.0"
bytes = "1.3.0"
oneshot = "0.1.5"
chashmap = "2.2.2"
futures = "0.3.25"
async-trait = "0.1.61"
color-eyre = "0.6.2"
anyhow = "1.0.68"
structopt = "0.3.26"
lazy_static = "1.4.0"
sled = "0.34.7"
thread-id = "4.0.0"
rand = "0.8.5"
dashmap = "5.4.0"
log4rs = "1.2.0"
#console-subscriber = "0.1.8"

[build-dependencies]
tonic-build = "0.8.4"
prost-build = "0.11.6"
