[package]
name = "mesg"
version = "0.1.0"
authors = ["ZOXEXIVO <zoxexivo@gmail.com>"]
edition = "2018"


[dependencies]
tokio = { version = "1.1.1", features = ["full"] }
toml = "0.5.8"
lz4 = "1.23.2"
serde = "1.0.123"
tonic = "0.4.0"
prost = "0.7.0"
timer = "0.2.0"
chrono = "0.4.19"
dashmap = "4.0.2"
log = { version = "0.4.14", features = ["release_max_level_info"] }
env_logger = "0.8.2"
clap = "2.33.3"
bytes = "1.0.1"
oneshot = "0.1.2"

[build-dependencies]
tonic-build = "0.4.0"
