[package]
name = "mesg-integration-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", features = ["full"] }
tonic = "0.7.2"
prost = "0.10.4"

[build-dependencies]
tonic-build = "0.7.2"
