[package]
name = "mesg-integration-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
tonic = "0.12.3"
prost = "0.13.5"

[build-dependencies]
tonic-build = "0.12.3"
