[package]
name = "mesg-integration-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
tonic = "0.8.2"
prost = "0.11.2"

[build-dependencies]
tonic-build = "0.8.2"
