[package]
name = "mesg-integration-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.14.0", features = ["full"] }
tonic = "0.6.1"
prost = "0.9.0"

[build-dependencies]
tonic-build = "0.6.0"