[package]
name = "mesg-integration-tests"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
tonic = "0.14.2"
tonic-prost = "0.14.2"
prost = "0.14.1"

[build-dependencies]
tonic-prost-build = "0.14.2"
