[package]
name = "mesg-integration-testing"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.0", features = ["full"] }
tonic = "0.8.1"
prost = "0.11.0"

[build-dependencies]
tonic-build = "0.8.0"
